### ISSUE TITLE
编译内核模块出错

### ISSUE THREAD

**Issue by YoungGeen** [DockDroid/openvmi#11]
/home/yangjin/openvmi/kernel/binder/binder.c: In function ‘task_get_unused_fd_flags’:
/home/yangjin/openvmi/kernel/binder/binder.c:445:12: error: implicit declaration of function ‘__alloc_fd’ [-Werror=implicit-function-declaration]
  445 |     return __alloc_fd(files, 0, rlim_cur, flags);
      |            ^~~~~~~~~~
/home/yangjin/openvmi/kernel/binder/binder.c: In function ‘task_fd_install’:
/home/yangjin/openvmi/kernel/binder/binder.c:455:9: error: implicit declaration of function ‘__fd_install’; did you mean ‘fd_install’? [-Werror=implicit-function-declaration]
  455 |         __fd_install(proc->files, fd, file);
      |         ^~~~~~~~~~~~
      |         fd_install
/home/yangjin/openvmi/kernel/binder/binder.c: In function ‘task_close_fd’:
/home/yangjin/openvmi/kernel/binder/binder.c:468:14: error: implicit declaration of function ‘__close_fd’; did you mean ‘close_fd’? [-Werror=implicit-function-declaration]
  468 |     retval = __close_fd(proc->files, fd);
      |              ^~~~~~~~~~
      |              close_fd
/home/yangjin/openvmi/kernel/binder/binder.c: In function ‘binder_update_page_range’:
/home/yangjin/openvmi/kernel/binder/binder.c:634:25: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  634 |         down_write(&mm->mmap_sem);
      |                         ^~~~~~~~
      |                         mmap_base
/home/yangjin/openvmi/kernel/binder/binder.c:684:23: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  684 |         up_write(&mm->mmap_sem);
      |                       ^~~~~~~~
      |                       mmap_base
/home/yangjin/openvmi/kernel/binder/binder.c:711:23: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  711 |         up_write(&mm->mmap_sem);
      |                       ^~~~~~~~
      |                       mmap_base
/home/yangjin/openvmi/kernel/binder/binder.c: In function ‘binder_mmap’:
/home/yangjin/openvmi/kernel/binder/binder.c:3487:19: error: implicit declaration of function ‘get_files_struct’; did you mean ‘put_files_struct’? [-Werror=implicit-function-declaration]
 3487 |     proc->files = get_files_struct(current);
      |                   ^~~~~~~~~~~~~~~~
      |                   put_files_struct
cc1: some warnings being treated as errors
scripts/Makefile.build:288: recipe for target '/home/yangjin/openvmi/kernel/binder/binder.o' failed
make[2]: *** [/home/yangjin/openvmi/kernel/binder/binder.o] Error 1
Makefile:1849: recipe for target '/home/yangjin/openvmi/kernel/binder' failed
make[1]: *** [/home/yangjin/openvmi/kernel/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-43-generic'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by maxingrong1213** [comment]
你的内核版本太高了，降到5.8以下再编译试试
