### ISSUE TITLE
拉取AOSP需要多大磁盘，500G都满了，还不够

### ISSUE THREAD

**Issue by Hanniballol** [DockDroid/openvmi#12]
拉取AOSP需要多大磁盘，500G都满了，还不够

**Comment by maxingrong1213** [comment]
Android7完整工程也就30G，怎么用到500G了？

**Comment by Hanniballol** [comment]
@maxingrong1213  加你wx了，方便通过下吗?
按照文档执行命令。repo init -u https://github.com/DockDroid/platform_manifests.git -b openvmi 这里初始化客户端是不是原因

**Comment by Hanniballol** [comment]
命令行 按文档来，没有动过
