### ISSUE TITLE
arm架构问题

### ISSUE THREAD

**Issue by Hanniballol** [DockDroid/openvmi#14]
编译img镜像 跟部署k8s 都需要arms架构吗？
二者需要在同一个服务器内进行吗？可分开执行吗？

docker run -it --privileged android:openvmi /bin/bash
docker: Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled

**Comment by zj-vmi** [comment]
1、Android容器与k8s可部署在同一台服务器，也可分开部署。
2、Android容器必须为ARM架构；k8s可为ARM或X86架构；
