### ISSUE TITLE
netd服务进程起不来

### ISSUE THREAD

**Issue by luoshuai5** [DockDroid/openvmi#3]
--------- beginning of system
__bionic_open_tzdata_path: ANDROID_ROOT not set!
05-17 05:07:06.004    17    17 I vold    : Vold 3.0 (the awakening) firing up
05-17 05:07:06.004    17    17 V vold    : Detected support for: ext4 vfat
05-17 05:07:06.005    17    17 E vold    : Failed to open default fstab /fstab.goldfish: Operation not permitted
05-17 05:07:06.005    17    17 E vold    : Error reading configuration... continuing anyways: Operation not permitted
05-17 05:07:06.027    17    26 D vold    : e4crypt_init_user0
05-17 05:07:06.027    17    26 D vold    : e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 1
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/system/users/0
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/misc/profiles/cur/0
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/misc/profiles/cur/0/foreign-dex
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/system_de/0
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/misc_de/0
05-17 05:07:06.027    17    26 D vold    : Preparing: /data/user_de/0
05-17 05:07:06.027    17    26 D vold    : e4crypt_unlock_user_key 0 serial=0 token_present=0
05-17 05:07:06.027    17    26 E vold    : Failed to chmod /data/system_ce/0: No such file or directory
05-17 05:07:06.027    17    26 E vold    : Failed to chmod /data/misc_ce/0: No such file or directory
05-17 05:07:06.027    17    26 E vold    : Failed to chmod /data/media/0: No such file or directory
--------- beginning of main
05-17 05:07:06.028     1     1 I vdc     : 200 18 Command succeeded
05-17 05:07:06.031    27    27 I /system/bin/tzdatacheck: tzdata file /data/misc/zoneinfo/current/tzdata does not exist. No action required.
05-17 05:07:06.037    30    30 I qemu-props: connected to 'boot-properties' qemud service.
05-17 05:07:06.037    30    30 I qemu-props: receiving..
05-17 05:07:06.037    30    30 I qemu-props: received: ro.sf.lcd_density=160
05-17 05:07:06.038    30    30 I qemu-props: receiving..
05-17 05:07:06.038    30    30 I qemu-props: exiting (1 properties set).
05-17 05:07:06.040    40    40 I         : installd firing up
05-17 05:07:06.040    40    40 E cutils  : Failed to read /data/.layout_version: No such file or directory
05-17 05:07:06.040    40    40 D         : Assuming that device has multi-user storage layout; upgrade no longer supported
05-17 05:07:06.040    40    40 D         : Upgrading to /data/misc/user directories
05-17 05:07:06.041    49    49 I perfprofd: starting Android Wide Profiling daemon
05-17 05:07:06.041    49    49 E perfprofd: unable to open configuration file /data/data/com.google.android.gms/files/perfprofd.conf
05-17 05:07:06.041    49    49 I perfprofd: random seed set to 4128588628
05-17 05:07:06.046    41    41 I keystore: Found keymaster0 module Keymaster OpenSSL HAL, version 2
05-17 05:07:06.046    41    41 I SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 131: Creating device
05-17 05:07:06.046    41    41 D SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 132: Device address: 0xffffa823d000
05-17 05:07:06.046    41    41 I keystore: Keymaster0 module is software-only.  Using SoftKeymasterDevice instead.
05-17 05:07:06.046    41    41 I SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 131: Creating device
05-17 05:07:06.046    41    41 D SoftKeymaster: system/keymaster/soft_keymaster_device.cpp, Line 132: Device address: 0xffffa823d400
05-17 05:07:06.046    41    41 I keystore: SELinux: Keystore SELinux is disabled.
05-17 05:07:06.046    47    47 I fingerprintd: Starting fingerprintd
05-17 05:07:06.047    48    48 I gatekeeperd: Starting gatekeeperd...
05-17 05:07:06.047    48    48 W gatekeeperd: falling back to software GateKeeper
05-17 05:07:06.047    48    48 I gatekeeperd: cold boot: clearing state
05-17 05:07:06.047    34    34 E DispSync: Couldn't set SCHED_FIFO for DispSyncThread
05-17 05:07:06.047    34    34 I SurfaceFlinger: SurfaceFlinger is starting
05-17 05:07:06.047    34    34 I SurfaceFlinger: SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
05-17 05:07:06.047    34    34 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
05-17 05:07:06.047    34    34 E libEGL  : load_driver(/system/lib64/egl/libGLES_emulation.so): dlopen failed: library "/system/lib64/egl/libGLES_emulation.so" not found
05-17 05:07:06.048    34    34 D libEGL  : loaded /system/lib64/egl/libEGL_emulation.so
05-17 05:07:06.049    34    34 D libEGL  : loaded /system/lib64/egl/libGLESv1_CM_emulation.so
05-17 05:07:06.053    34    34 D libEGL  : loaded /system/lib64/egl/libGLESv2_emulation.so
05-17 05:07:06.057    34    34 D         : HostConnection::get() New Host Connection established 0xffff9363c0c0, tid 34
05-17 05:07:06.059    34    34 E SurfaceFlinger: Couldn't set SCHED_FIFO for SFEventThread
05-17 05:07:06.059    34    34 D hwcomposer: int hwc_device_open(const hw_module_t *, const char *, hw_device_t **)
05-17 05:07:06.059    34    34 I SurfaceFlinger: Using composer version 1.0
05-17 05:07:06.060    34    34 W SurfaceFlinger: no suitable EGLConfig found, trying a simpler query
05-17 05:07:06.060    34    34 I SurfaceFlinger: EGL information:
05-17 05:07:06.060    34    34 I SurfaceFlinger: vendor    : Android
05-17 05:07:06.060    34    34 I SurfaceFlinger: version   : 1.4 Android META-EGL
05-17 05:07:06.060    34    34 I SurfaceFlinger: extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_create_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer
05-17 05:07:06.060    34    34 I SurfaceFlinger: Client API: OpenGL_ES
05-17 05:07:06.060    34    34 I SurfaceFlinger: EGLSurface: 8-8-8-8, config=0x2d
05-17 05:07:06.063    34    34 I SurfaceFlinger: OpenGL ES informations:
05-17 05:07:06.063    34    34 I SurfaceFlinger: vendor    : Google Inc.
05-17 05:07:06.063    34    34 I SurfaceFlinger: renderer  : Google SwiftShader
05-17 05:07:06.063    34    34 I SurfaceFlinger: version   : OpenGL ES 2.0
05-17 05:07:06.063    34    34 I SurfaceFlinger: extensions: GL_EXT_debug_marker GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_framebuffer_object GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_texture_3D GL_OES_vertex_array_object GL_OES_vertex_half_float GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_draw_buffers GL_EXT_float_blend GL_EXT_instanced_arrays GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_ARB_texture_rectangle GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_inst
05-17 05:07:06.063    34    34 I SurfaceFlinger: GL_MAX_TEXTURE_SIZE = 8192
05-17 05:07:06.063    34    34 I SurfaceFlinger: GL_MAX_VIEWPORT_DIMS = 8192
05-17 05:07:06.063    34    34 E cutils-trace: Error opening trace file: Permission denied (13)
05-17 05:07:06.121    34    34 D SurfaceFlinger: shader cache generated - 24 shaders in 54.619793 ms
05-17 05:07:06.121    34    34 E SurfaceFlinger: Couldn't set SCHED_FIFO
05-17 05:07:06.121    34    34 D SurfaceFlinger: Set power mode=2, type=0 flinger=0xffff93647000
05-17 05:07:06.121    34    63 E SurfaceFlinger: eventControl(0, 1) failed Bad address
05-17 05:07:06.121    34    34 W SurfaceFlinger: Couldn't set SCHED_FIFO on display on
05-17 05:07:06.244    64    64 I BootAnimation: boot animation disabled
05-17 05:08:56.972   688   688 I Netd    : Netd 1.0 starting
05-17 05:08:56.972   688   688 D TetherController: Setting IP forward enable = 0
05-17 05:08:56.972   688   688 E TetherController: Failed to open /proc/sys/net/ipv4/ip_forward: Read-only file system
05-17 05:08:56.972   688   688 E TetherController: Failed to open /proc/sys/net/ipv6/conf/all/forwarding: Read-only file system
05-17 05:08:56.983   688   688 E Netd    : cannot find interface dummy0
05-17 05:08:56.984   688   688 E Netd    : Unable to create netlink socket: Protocol not supported
05-17 05:08:56.984   688   688 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
05-17 05:08:56.984   688   688 D MDnsDS  : MDnsSdListener::Hander starting up
05-17 05:08:56.984   688   695 D MDnsDS  : MDnsSdListener starting to monitor
05-17 05:08:56.984   688   695 D MDnsDS  : Going to poll with pollCount 1
05-17 05:09:01.002    33    33 I ServiceManager: service 'netd' died
05-17 05:09:02.016   731   731 I Netd    : Netd 1.0 starting
05-17 05:09:02.016   731   731 D TetherController: Setting IP forward enable = 0
05-17 05:09:02.016   731   731 E TetherController: Failed to open /proc/sys/net/ipv4/ip_forward: Read-only file system
05-17 05:09:02.016   731   731 E TetherController: Failed to open /proc/sys/net/ipv6/conf/all/forwarding: Read-only file system
05-17 05:09:02.027   731   731 E Netd    : cannot find interface dummy0
05-17 05:09:02.028   731   731 E Netd    : Unable to create netlink socket: Protocol not supported
05-17 05:09:02.028   731   731 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
05-17 05:09:02.029   731   731 D MDnsDS  : MDnsSdListener::Hander starting up
05-17 05:09:02.029   731   738 D MDnsDS  : MDnsSdListener starting to monitor
05-17 05:09:02.029   731   738 D MDnsDS  : Going to poll with pollCount 1
05-17 05:09:06.050    33    33 I ServiceManager: service 'netd' died
05-17 05:09:07.076   767   767 I Netd    : Netd 1.0 starting
05-17 05:09:07.076   767   767 D TetherController: Setting IP forward enable = 0
05-17 05:09:07.076   767   767 E TetherController: Failed to open /proc/sys/net/ipv4/ip_forward: Read-only file system
05-17 05:09:07.076   767   767 E TetherController: Failed to open /proc/sys/net/ipv6/conf/all/forwarding: Read-only file system
05-17 05:09:07.086   767   767 E Netd    : cannot find interface dummy0
05-17 05:09:07.088   767   767 E Netd    : Unable to create netlink socket: Protocol not supported
05-17 05:09:07.088   767   767 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
05-17 05:09:07.088   767   767 D MDnsDS  : MDnsSdListener::Hander starting up
05-17 05:09:07.088   767   774 D MDnsDS  : MDnsSdListener starting to monitor
05-17 05:09:07.088   767   774 D MDnsDS  : Going to poll with pollCount 1
05-17 05:09:11.106    33    33 I ServiceManager: service 'netd' died
05-17 05:09:12.124   810   810 I Netd    : Netd 1.0 starting
05-17 05:09:12.124   810   810 D TetherController: Setting IP forward enable = 0
05-17 05:09:12.124   810   810 E TetherController: Failed to open /proc/sys/net/ipv4/ip_forward: Read-only file system
05-17 05:09:12.124   810   810 E TetherController: Failed to open /proc/sys/net/ipv6/conf/all/forwarding: Read-only file system
05-17 05:09:12.134   810   810 E Netd    : cannot find interface dummy0
05-17 05:09:12.136   810   810 E Netd    : Unable to create netlink socket: Protocol not supported
05-17 05:09:12.136   810   810 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
05-17 05:09:12.136   810   810 D MDnsDS  : MDnsSdListener::Hander starting up
05-17 05:09:12.136   810   817 D MDnsDS  : MDnsSdListener starting to monitor
05-17 05:09:12.136   810   817 D MDnsDS  : Going to poll with pollCount 1
05-17 05:09:16.158    33    33 I ServiceManager: service 'netd' died

**Comment by maxingrong1213** [comment]
关于在编译纯64bit Android 镜像时libavc的报错，可以在/external/libavc/Android.mk修改为：
```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ARCH_ARM_HAVE_NEON:=true

include $(LOCAL_PATH)/encoder.mk
include $(LOCAL_PATH)/decoder.mk
```
再编译纯64bit镜像来测试。
