### ISSUE TITLE
在创建虚拟机的时候一直卡着不动啥情况

### ISSUE THREAD

**Issue by TangJhan** [DockDroid/openvmi#6]
root@ecs-kc1-large-2-linux-20211014134526:~# cd cloud-platform/tools
root@ecs-kc1-large-2-linux-20211014134526:~/cloud-platform/tools# ./android-vm-manage.sh create - 1
START CREATE 1 VMs...
create ecs-kc1-large-2-linux-20211014134526-01...

**Comment by maxingrong1213** [comment]
你可以去/opt/openvmi/目录中获取对应云机的启动log

**Comment by Hanniballol** [comment]
@TangJhan  你那里是如何处理的？我也遇到相同的问题，/opt/openvmi/目录无日志
