### ISSUE TITLE
出现GMock错误

### ISSUE THREAD

**Issue by kfcx** [DockDroid/openvmi#7]
为什么我在执行 ”make -j8 install“ 这条命令时报错

  No download step for 'GMock'
  [  7%] No patch step for 'GMock'
  [  8%] No update step for 'GMock'
  [  9%] Performing configure step for 'GMock'
... ...
[ 75%] Built target gmock
Scanning dependencies of target gmock_main
[ 87%] Building CXX object CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[100%] Linking CXX static library lib/libgmock_main.a
[100%] Built target gmock_main
[ 29%] No install step for 'GMock'
[ 30%] Completed 'GMock'
[ 30%] Built target GMock
make: *** [Makefile:141: all] Error 2

Google并没有想要的答案，求帮助-Help-SOS-

**Comment by maxingrong1213** [comment]
应该是下载的源配置问题
