### ISSUE TITLE
云手机内调用pm list packages 显示 Could not access the Package Manager. Is the system running

### ISSUE THREAD

**Issue by JustForImprove** [DockDroid/openvmi#8]
按步骤启动并通过adb连接进去后，调用pm list packages 显示 Could not access the Package Manager. Is the system running, 启动命令是android-vm-manager create - 1, 请问是哪里的问题？

**Comment by maxingrong1213** [comment]
ps看下系统完整启动了吗？

**Comment by JustForImprove** [comment]
![捕获](https://user-images.githubusercontent.com/33738171/162716382-5f066d13-08fc-4fbf-925d-f1f7340d5e0c.PNG)

**Comment by maxingrong1213** [comment]
你的系统还没起来，要logcat看下哪儿出问题了

**Comment by JustForImprove** [comment]
[log.txt](https://github.com/DockDroid/openvmi/files/8463101/log.txt)

**Comment by JustForImprove** [comment]
这是部分日志

**Comment by maxingrong1213** [comment]
你的Android源码是通过这个xml去repo下载下来的吗？https://github.com/DockDroid/platform_manifests

**Comment by JustForImprove** [comment]
这是其他人编译的，他是运行成功的，不过是通过docker启动

**Comment by JustForImprove** [comment]
如果是镜像有问题，可以提供一份能运行的镜像吗？我们希望能尽快看到效果。

**Comment by maxingrong1213** [comment]
这个开源项目很久没维护了，我这没有编译好的镜像了，你也可以用尝试采用docker的方式启动。

**Comment by JustForImprove** [comment]
好吧，，

**Comment by Hanniballol** [comment]
> 好吧，，

请问docker启动是如何操作的，我这边提示bash找不到
