### ISSUE TITLE
Android镜像编译失败

### ISSUE THREAD

**Issue by ddynwzh1992** [DockDroid/openvmi#9]
编译Android系统源码时执行 make -j32 报错，报错信息如下：
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_PRODUCT=openvmi_arm64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a15
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-1071-aws-x86_64-with-Ubuntu-18.04-bionic
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=N6F26Q
OUT_DIR=/home/ubuntu/test/openvmi-work
============================================
Running kati to generate build-openvmi_arm64.ninja...
./android/lights/Android.mk was modified, regenerating...
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_PRODUCT=openvmi_arm64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a15
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-1071-aws-x86_64-with-Ubuntu-18.04-bionic
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=N6F26Q
OUT_DIR=/home/ubuntu/test/openvmi-work
============================================
Clean step: rm -rf /home/ubuntu/test/openvmi-work/target/common/obj/SHARED_LIBRARIES/libGLES_emul_intermediates
Clean step: rm -rf /home/ubuntu/test/openvmi-work/target/common/obj/SHARED_LIBRARIES/libGLES_emul_intermediates
including ./Android.mk ...
Starting build with ninja
ninja: Entering directory `.'
ninja: error: '/home/ubuntu/test/openvmi-work/target/common/obj/PACKAGING/public_api.txt', needed by '/home/ubuntu/test/openvmi-work/target/common/obj/PACKAGING/checkpublicapi-last-timestamp', missing and no known rule to make it
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (2 seconds) ####

操作系统：
Linux ip-10-0-1-253 5.4.0-1071-aws #76~18.04.1-Ubuntu SMP Mon Mar 28 17:49:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by maxingrong1213** [comment]
你的Android源码repo完整了吗？再确认下Android 7编译需要的系统依赖安装完整没。
